# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 756b0e23f11345b51d02adb78672406dcdc6b46b992859bfbf598c544122ce98d91d66be239187c9719eeda77c50a7d58d89756c60205788fbd60d3a66fc1eb0

test:
  secret_key_base: db671dee8391a60aa7e7c82fe719acf459e0c2602fd3c35feed09ed016b1a46fa1a66fcba8442cb55635216f4ab085141e8f356540871914decd7b4df697aa97

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid_username: your-sendgrid-username
  sendgrid_password: your-sendgrid-password